### ISSUE TITLE
[1.17.1] Crash in REI in latest version

### ISSUE THREAD

**Issue by Muffintiem** [kwpugh/gobber_fabric-1.17#10]
When I browse REI using the latest version I'm getting a crash. Crash log is as follows:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/15/21, 11:57 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_897.method_23169(net.minecraft.class_1297, float)" because "â˜ƒ" is null
	at net.minecraft.class_898.method_3954(class_898.java:128)
	at io.github.lucaargolo.entitybanners.client.EntityBannersClient.drawEntityOnCanvas(EntityBannersClient.java:46)
	at net.minecraft.class_823.md1fe44f$lambda$renderCanvas$0$0(class_823.java:547)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
	at net.minecraft.class_823.handler$zne000$renderCanvas(class_823.java:535)
	at net.minecraft.class_823.method_23802(class_823.java:142)
	at net.minecraft.class_823.method_29999(class_823.java:129)
	at net.minecraft.class_823.method_3546(class_823.java:122)
	at net.minecraft.class_823.method_3569(class_823.java:30)
	at net.minecraft.class_824.method_23080(class_824.java:92)
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_23077(class_824.java:92)
	at net.minecraft.class_756.method_3166(class_756.java:139)
	at net.minecraft.class_918.method_23179(class_918.java:132)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:265)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:197)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:141)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderEntries(BatchedEntryRendererManager.java:115)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:94)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:259)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:585)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:491)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:318)
	at net.minecraft.class_757.handler$zjh000$renderScreenPost(class_757.java:1539)
	at net.minecraft.class_757.method_3192(class_757.java:874)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
Details:
	Entity Type: gobber2:nemesis_nether (com.kwpugh.gobber2.entities.NemesisEntityNether)
	Entity ID: 718
	Entity Name: entity.gobber2.nemesis_nether
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: ~~NULL~~
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 0.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:128)
	at io.github.lucaargolo.entitybanners.client.EntityBannersClient.drawEntityOnCanvas(EntityBannersClient.java:46)
	at net.minecraft.class_823.md1fe44f$lambda$renderCanvas$0$0(class_823.java:547)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
	at net.minecraft.class_823.handler$zne000$renderCanvas(class_823.java:535)
	at net.minecraft.class_823.method_23802(class_823.java:142)
	at net.minecraft.class_823.method_29999(class_823.java:129)
	at net.minecraft.class_823.method_3546(class_823.java:122)
	at net.minecraft.class_823.method_3569(class_823.java:30)
	at net.minecraft.class_824.method_23080(class_824.java:92)

-- Block Entity Details --
Details:
	Name: minecraft:banner // net.minecraft.class_2573
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_23077(class_824.java:92)
	at net.minecraft.class_756.method_3166(class_756.java:139)
	at net.minecraft.class_918.method_23179(class_918.java:132)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:265)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:197)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:141)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderEntries(BatchedEntryRendererManager.java:115)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:94)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:259)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:585)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:491)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$18(RoughlyEnoughItemsCoreClient.java:318)
	at net.minecraft.class_757.handler$zjh000$renderScreenPost(class_757.java:1539)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (951, 10). Absolute: (1902.000000, 21.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['muffintiem'/145, l='ClientLevel', x=736.09, y=79.00, z=684.58]]
	Chunk stats: 841, 328
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,79,-16), Section: (at 0,15,0 in -15,4,-1; chunk contains blocks -240,-64,-16 to -225,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 594129 game time, 3407 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, 3D+Mushrooms+v1.1.zip, HMLM.zip, s33r-rainbow-amethyst.zip, MuddySlime.zip, VerdigrisCats.zip, BetterAzaleasv2.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 816249768 bytes (778 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Plus Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a52
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7870
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18583.47
	Virtual memory used (MB): 8536.66
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 44.20
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-xray-fabric: Advanced XRay (Fabric) 0.6.0-build.8
		allstackable: All Stackable 1.4.0
		aqupd: Caracal mob 1.17-1.3.0
		architectury: Architectury 2.0.9
		bannerpp: Banner++ 2.0.3+mc.1.17-rc1
		bclib: BCLib 0.3.1
		beenfo: Beenfo 1.17-fabric0.34.9-1.3.1
		betterend: Better End 0.11.0-pre
		betternether: Better Nether 5.1.3
		biomeinfo: Biome Info 1.17-7
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.1-1.17
		cardinal-components: Cardinal Components API 3.0.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.0.0
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.0
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.37
		comforts: Comforts 0.0.5-1.17.1
		cosmetic-armor: Cosmetic Armor 1.1.0
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		earthtojavamobs: Earth2Java 1.7.1+1.17
		emerald_tools: Emerald Tools 1.2.26
		entitybanners: Entity Banners 1.0.2-BETA+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		explorerscompass: Explorer's Compass 1.17.1-2.0.1-fabric
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fastchest: FastChest 1.2+1.17
		fastfurnace: FastFurnace 1.17-3.0
		ferritecore: FerriteCore 3.0.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.5
		gimme_bundles: Gimme bundles! 1.0.2
		gobber2: Gobber2 2.4.37
		hookshot: Hookshot 16.0
		indypets: Independent Pets 0.5.0
		java: OpenJDK 64-Bit Server VM 16
		lithium: Lithium 0.7.3
		lowfire: Low Fire 1.17-2.0.0
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		magic_mirror: Magic Mirror 1.3.1
		mavm: More Axolotl Variants Mod 1.0.2b
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.4
		mooblooms: Mooblooms 1.5.1
		multipart_entities: MultipartEntities 1.1.2-1.17
		musicdr: Music Duration Reducer 1.2.1
		naturescompass: Nature's Compass 1.17.1-2.0.0-fabric
		nha: Netherite Horse Armor 1.2.0
		onsoulfire: On Soul Fire 1.17-3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		outvoted: Outvoted 2.0.0-alpha.12
		pettable: Pettable 1.2.0
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		simple_backpack: SimpleBackpack 1.1.18
		somnus: Somnus API 0.0.12-1.17
		stackablepotions: Stackable Potions 1.0.0
		statuseffecttimer: Status Effect Timer 1.0.2
		terralith: Terralith for Fabric 1.3.1
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		torohealth: ToroHealth Damage Indicators 1.17-fabric-6
		totemplus: Totem Plus 1.1
		trinkets: Trinkets 3.0.2
		villagernames: Villager Names 2.0.0
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) Iris(R) Plus Graphics GL version 3.2.0 - Build 26.20.100.7870, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/3D+Mushrooms+v1.1.zip, file/HMLM.zip, file/s33r-rainbow-amethyst.zip, file/MuddySlime.zip, file/VerdigrisCats.zip, file/BetterAzaleasv2.zip, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Player Count: 1 / 8; [class_3222['muffintiem'/145, l='ServerLevel[terralithtest3]', x=736.09, y=79.00, z=684.58]]
	Data Packs: vanilla, Fabric Mods

**Comment by kwpugh** [comment]
if you have nemesis enabled in the config, disable it for now, it is experimental.

**Comment by Muffintiem** [comment]
It does it even if I set it to false. Tbh REI should really only show items that have craftable recipes. You can only get Entity Banners by fighting mobs. Of course I dunno if it causes a crash when I obtain the banner because you need to kill 50 to obtain a banner but maybe I'll try and let you know what happens.

**Comment by Muffintiem** [comment]
Ok so I tested it and the banner itself works fine. I'm honestly really liking the Nemesis. It's like a silverfish that only inhabits Gobber Ores.

**Comment by kwpugh** [comment]
I put the nemesis into the blacklist and the banners don't generate or show up in REI.

  "blacklistedEntities": ["gobber2:nemesis","gobber2:nemesis_nether","gobber2:nemesis_end"]

Until I sort this out.

**Comment by kwpugh** [comment]
I'm horrible at textures, I really need to get a better texture for the nemesis

**Comment by Muffintiem** [comment]
I don't think it's that bad. It fits in well with the game.

**Comment by kwpugh** [comment]
Hopefully work towards a better. one.

**Comment by kwpugh** [comment]
Open issue with Entity Banners mod regarding the REI crash.

https://github.com/lucaargolo/entity-banners/issues/2

**Comment by Muffintiem** [comment]
Yeah tbh the banners shouldn't even show up at all since they can't be crafted.

**Comment by kwpugh** [comment]
this will be fixed in next update, v2.4.39
