### ISSUE TITLE
Few unknown items

### ISSUE THREAD

**Issue by Yucked** [kwpugh/gobber_fabric-1.17#33]
Latest Fabric API already loaded, unsure if it's conflicting with charms mod
```
[18:33:23] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_helmet_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_helmet_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:23] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_boots_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_boots_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:23] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_leggings_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_leggings_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:23] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_chestplate_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_chestplate_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
        at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:23] [Worker-Main-1/INFO]: Loaded 9 recipes
[18:33:24] [Worker-Main-1/INFO]: Loaded 1366 advancements
[18:33:24] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_helmet_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_helmet_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_20705(SortingRecipeManager.java:25) ~[charm-fabric-1.17-3.3.2.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_18788(SortingRecipeManager.java:16) ~[charm-fabric-1.17-3.3.2.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:24] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_boots_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_boots_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_20705(SortingRecipeManager.java:25) ~[charm-fabric-1.17-3.3.2.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_18788(SortingRecipeManager.java:16) ~[charm-fabric-1.17-3.3.2.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:24] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_leggings_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_leggings_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_20705(SortingRecipeManager.java:25) ~[charm-fabric-1.17-3.3.2.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_18788(SortingRecipeManager.java:16) ~[charm-fabric-1.17-3.3.2.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[18:33:24] [Worker-Main-1/ERROR]: Parsing error loading recipe gobber2:gobber2_chestplate_dragon_no_flight
com.google.gson.JsonSyntaxException: Unknown item 'gobber2:gobber2_chestplate_dragon_no_flight'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:87) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_20705(SortingRecipeManager.java:25) ~[charm-fabric-1.17-3.3.2.jar:?]
        at svenhjol.charm.module.core.SortingRecipeManager.method_18788(SortingRecipeManager.java:16) ~[charm-fabric-1.17-3.3.2.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by kwpugh** [comment]
That is from the disabled armor item.  Its fine.

**Comment by Yucked** [comment]
Any plans on removing it or suppressing those exceptions?

**Comment by kwpugh** [comment]
Nope.  it is part of minecraft/fabric.  the parses all the recipes and if it finds recipes for items that are not registered in the game, it spits out the warnings.  par for the course.
