### ISSUE TITLE
[1.18] Mineable tag issue

### ISSUE THREAD

**Issue by MunchyG** [kwpugh/gobber_fabric-1.17#34]
i am getting a crash that i can't explain (pretty sure kubejs is doing something and breaking it but honestly have no idea)

[14:07:57] [Worker-Main-3/ERROR]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: gobber2:gobber2_ore (from Gobber2),gobber2:gobber2_ore_nether (from Gobber2),gobber2:gobber2_ore_end (from Gobber2),gobber2:gobber2_block (from Gobber2),gobber2:gobber2_block_nether (from Gobber2),gobber2:gobber2_block_end (from Gobber2),gobber2:gobber2_lucky_block (from Gobber2),gobber2:gobber2_glass (from Gobber2),gobber2:gobber2_glass_nether (from Gobber2),gobber2:gobber2_glass_end (from Gobber2),gobber2:clear_glass (from Gobber2)
[14:07:57] [Worker-Main-3/ERROR]: Couldn't load tag minecraft:needs_diamond_tool as it is missing following references: gobber2:gobber2_ore (from Gobber2),gobber2:gobber2_block (from Gobber2),gobber2:gobber2_glass (from Gobber2)
[14:07:57] [Worker-Main-3/ERROR]: Couldn't load tag minecraft:needs_iron_tool as it is missing following references: gobber2:gobber2_lucky_block (from Gobber2),gobber2:clear_glass (from Gobber2)
[14:07:57] [Worker-Main-3/ERROR]: Couldn't load tag fabric:needs_tool_level_4 as it is missing following references: gobber2:gobber2_ore_nether (from Gobber2),gobber2:gobber2_block_nether (from Gobber2),gobber2:gobber2_glass_nether (from Gobber2)
[14:07:57] [Worker-Main-3/ERROR]: Couldn't load tag fabric:needs_tool_level_5 as it is missing following references: gobber2:gobber2_ore_end (from Gobber2),gobber2:gobber2_block_end (from Gobber2),gobber2:gobber2_glass_end (from Gobber2)
[14:07:58] [Worker-Main-4/ERROR]: Error occurred while handling event 'items.tags': Error: Missing namespace gobber2 in the unification order: techreborn,indrev,modern_industrialization,charm,appliedenergistics2. Required by item gobber2:diamond_nugget in tag c:diamond_nuggets. (server_scripts:unification/materials.js#95)
[14:07:58] [Worker-Main-4/INFO]: [items] Found 1156 tags, added 0 objects, removed 31 objects
[14:07:58] [Worker-Main-4/ERROR]: Couldn't load tag c:uncommon_loot as it is missing following references: gobber2:gobber2_ingot (from Gobber2)
[14:07:58] [Worker-Main-4/ERROR]: Couldn't load tag c:diamond_nuggets as it is missing following references: gobber2:diamond_nugget (from Gobber2)
[14:07:58] [Worker-Main-4/ERROR]: Couldn't load tag c:very_rare_loot as it is missing following references: gobber2:gobber2_ingot_end (from Gobber2),gobber2:gobber2_ring_teleport (from Gobber2),gobber2:gobber2_ring_ascent (from Gobber2),gobber2:gobber2_ring_swiftness (from Gobber2)
[14:07:58] [Worker-Main-4/ERROR]: Couldn't load tag origins:meat as it is missing following references: gobber2:gobber2_gooey_beef (from Gobber2),gobber2:gobber2_gooey_beefstew (from Gobber2),gobber2:gobber2_gooey_beef_nether (from Gobber2),gobber2:gobber2_gooey_beefstew_nether (from Gobber2)
[14:07:58] [Worker-Main-4/ERROR]: Couldn't load tag origins:ranged_weapons as it is missing following references: gobber2:gobber2_bow (from Gobber2),gobber2:gobber2_bow_nether (from Gobber2),gobber2:gobber2_bow_end (from Gobber2),gobber2:gobber2_sword_sniper (from Gobber2),gobber2:gobber2_staff_sniper (from Gobber2)
[14:07:58] [Worker-Main-4/ERROR]: Couldn't load tag c:rare_loot as it is missing following references: gobber2:gobber2_ingot_nether (from Gobber2),gobber2:gobber2_ring_return (from Gobber2),gobber2:gobber2_ring_attraction (from Gobber2),gobber2:gobber2_ring_sunshine (from Gobber2)
[14:07:59] [Worker-Main-5/INFO]: closing rrp modern_industrialization:general
[14:07:59] [Worker-Main-5/INFO]: closing rrp modern_industrialization:recipes
[14:07:59] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: ResourceKey[minecraft:root / minecraft:block]:minecraft:mineable/pickaxe,ResourceKey[minecraft:root / minecraft:block]:minecraft:needs_diamond_tool,ResourceKey[minecraft:root / minecraft:block]:minecraft:needs_iron_tool
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:151) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]
Caused by: java.lang.IllegalStateException: Missing required tags: ResourceKey[minecraft:root / minecraft:block]:minecraft:mineable/pickaxe,ResourceKey[minecraft:root / minecraft:block]:minecraft:needs_diamond_tool,ResourceKey[minecraft:root / minecraft:block]:minecraft:needs_iron_tool
	at net.minecraft.class_3505.method_33182(class_3505.java:55) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2143) ~[?:?]
	at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

**Comment by kwpugh** [comment]
I found some missing in my tag jsons.  Try this versions and let me know.
[Gobber2-Fabric-1.18-pre1-2.5.40.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/7546757/Gobber2-Fabric-1.18-pre1-2.5.40.jar.zip)

**Comment by kwpugh** [comment]
1.17.1 or 1.18-pre1 ?

**Comment by kwpugh** [comment]
Try this version and let me know.
[Gobber2-Fabric-1.17.1-2.4.60.jar.zip](https://github.com/kwpugh/gobber_fabric-1.17/files/7547000/Gobber2-Fabric-1.17.1-2.4.60.jar.zip)

**Comment by MunchyG** [comment]
it was 1.17.1, but I found out it was to do with a error with fabric loader 0.12.5, and reverting to 0.11.7 fixed the issue.
