### ISSUE TITLE
[1.17.1] StuffZ mod causing crashes with teleportation

### ISSUE THREAD

**Issue by sbdonslaught** [kwpugh/gobber_fabric-1.17#5]
Hello, 

Whenever I use the teleport ring, only the one where you set the location yourself, I get this crash error.

Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} as it does not exist in Block{minecraft:void_air}

	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.stuffz.block.entity.BrewingBarrelEntity.update(BrewingBarrelEntity.java:88)
	at net.stuffz.block.entity.BrewingBarrelEntity.clientTick(BrewingBarrelEntity.java:60)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_638.method_18116(class_638.java:171)
	at net.minecraft.class_310.method_1574(class_310.java:1752)
	at net.minecraft.class_310.method_1523(class_310.java:1083)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	

I have a full crash log in needed. 
Thank you.

**Comment by kwpugh** [comment]
yes, please post a link to full crash report

**Comment by sbdonslaught** [comment]
Here you go:
https://www.onslaught.ca/s/79vo7ti3.txt

**Comment by kwpugh** [comment]
I see you are a few version back, please try 2.4.30 of Gobber and see if you still get the error.

**Comment by kwpugh** [comment]
Also, the crash report shows Minecraft v 1.18 ?

**Comment by sbdonslaught** [comment]
Ahh, it was part of a larger mod pack I'm trying out. I'll update and reach out to the mod pack creators for them to update it as well! :) 

Thank you for the speedy replies!
Will re-open if it happens on new version.

**Comment by sbdonslaught** [comment]
> Also, the crash report shows Minecraft v 1.18 ?

Yes, they just label it as that, but it's 1.17.
https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric

If you'd like to take a closer look. (I'm new to the modded scene)

**Comment by kwpugh** [comment]
The crash report seems to indicate that the issue was with an brewing stand from StuffZ.  were you teleporting to its location with the ring when it crashed?

**Comment by sbdonslaught** [comment]
I wasn't teleporting to it, but from it. 

When i teleport to it (my home), everything seems fine.

**Comment by kwpugh** [comment]
I'm going to let GloBox know, see if it makes sense to him/her.

**Comment by sbdonslaught** [comment]
> Did you actually teleport before the crash?

1) I try to teleport, 
2) I crash,
3) I reload into the world, and I'm at the new location that I was trying to teleport to.

So I guess, it's "after" the teleport. but i never see myself at the new location.

**Comment by kwpugh** [comment]
Was the teleport location next to the brewing barrel?

**Comment by sbdonslaught** [comment]
> Was the teleport location next to the brewing barrel?
> 
> in the ring.

No, the set location was far away. I was in my house (where the barrel is) and I was trying to teleport to a cave somewhere else.

**Comment by kwpugh** [comment]
how near to a BrewingBarrel were you when you teleported?

**Comment by sbdonslaught** [comment]
I'd probably say.. it has happened when I was 20 blocks away and up to like 200 blocks.

**Comment by kwpugh** [comment]
I'm no longer going to track this one, not an issue with my code.
