### ISSUE TITLE
[1.18.1] Incompatability with Additional Adititions

### ISSUE THREAD

**Issue by 3prm3** [kwpugh/gobber_fabric-1.17#58]
[05/03/2022 17:04:40 PM] [main/WARN] @Inject(@At("INVOKE")) Shift.BY=2 on dripstone_fluid_lib.mixins.json:MinecraftClientMixin::handler$ckn000$dripstone_fluid_lib$handleParticles exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[05/03/2022 17:04:40 PM] [main/INFO] sodium-extra.mixins.json:gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[05/03/2022 17:04:45 PM] [main/INFO] alloygery.mixins.json:ItemAccessor->@Accessor[FIELD_GETTER]::getAttackDamageModifierId()Ljava/util/UUID; should be static as its target is
[05/03/2022 17:04:45 PM] [main/INFO] alloygery.mixins.json:ItemAccessor->@Accessor[FIELD_GETTER]::getAttackSpeedModifierId()Ljava/util/UUID; should be static as its target is
[05/03/2022 17:04:46 PM]  Expected: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;, Lnet/minecraft/class_2248;]
[05/03/2022 17:04:46 PM]     Found: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
[05/03/2022 17:04:46 PM] [main/WARN] Injection warning: LVT in net/minecraft/class_2404::method_10316(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Z has incompatible changes at opcode 120 in callback betternether.mixins.common.json:LiquidBlockMixin->@Inject::bn_shouldSpreadLiquid(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLcom/google/common/collect/UnmodifiableIterator;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;)V from mod betternether.Available: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
[05/03/2022 17:04:52 PM] Could not find code source for magic-at:/net/minecraft/class_1886$15.class: java.net.MalformedURLException: unknown protocol: magic-at
[05/03/2022 17:04:52 PM] [main/INFO] Gobber Mod Info Message: Max value of attribute.name.generic.armor is currently set to 80.0
[05/03/2022 17:04:56 PM] [main/WARN] @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$cpj000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[05/03/2022 17:05:01 PM] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
[05/03/2022 17:05:01 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
[05/03/2022 17:05:01 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[05/03/2022 17:05:01 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[05/03/2022 17:05:01 PM] Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_6862
[05/03/2022 17:05:01 PM] 	at com.kwpugh.pugh_tools.init.TagInit.<clinit>(TagInit.java:11)
[05/03/2022 17:05:01 PM] 	at com.kwpugh.pugh_tools.Tools.Paxel.<init>(Paxel.java:44)
[05/03/2022 17:05:01 PM] 	at com.kwpugh.gobber2.items.tools.basetools.ModPaxel.<init>(ModPaxel.java:22)
[05/03/2022 17:05:01 PM] 	at com.kwpugh.gobber2.init.ItemInit.<clinit>(ItemInit.java:114)
[05/03/2022 17:05:01 PM] 	at net.minecraft.item.ArmorItem.handler$dhh000$gobberConstructor(ArmorItem:1540)
[05/03/2022 17:05:01 PM] 	at net.minecraft.item.ArmorItem.<init>(ArmorItem:95)
[05/03/2022 17:05:01 PM] 	at dqu.additionaladditions.registry.AdditionalMaterials.<clinit>(AdditionalMaterials.java:18)
[05/03/2022 17:05:01 PM] 	at net.minecraft.item.ArmorItem.handler$zza000$constructor(ArmorItem:532)
[05/03/2022 17:05:01 PM] 	at net.minecraft.item.ArmorItem.<init>(ArmorItem:95)
[05/03/2022 17:05:01 PM] 	at net.minecraft.item.Items.<clinit>(Items:731)
[05/03/2022 17:05:01 PM] 	at net.minecraft.util.registry.Registry.method_10234(Registry:177)
[05/03/2022 17:05:01 PM] 	at net.minecraft.util.registry.Registry.method_34031(Registry:278)
[05/03/2022 17:05:01 PM] 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
[05/03/2022 17:05:01 PM] 	at net.minecraft.util.registry.Registry.<clinit>(Registry:277)
[05/03/2022 17:05:01 PM] 	at net.minecraft.Bootstrap.initialize(Bootstrap:49)
[05/03/2022 17:05:01 PM] 	at net.minecraft.client.main.Main.main(Main:155)
[05/03/2022 17:05:01 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05/03/2022 17:05:01 PM] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[05/03/2022 17:05:01 PM] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05/03/2022 17:05:01 PM] 	at java.lang.reflect.Method.invoke(Method.java:568)
[05/03/2022 17:05:01 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[05/03/2022 17:05:01 PM] 	... 2 more
[05/03/2022 17:05:01 PM] Caused by: java.lang.ClassNotFoundException: net.minecraft.class_6862
[05/03/2022 17:05:01 PM] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[05/03/2022 17:05:01 PM] 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[05/03/2022 17:05:01 PM] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[05/03/2022 17:05:01 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
[05/03/2022 17:05:01 PM] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[05/03/2022 17:05:01 PM] 	... 23 more
[05/03/2022 17:05:01 PM] [main/ERROR] Minecraft has crashed!

**Comment by kwpugh** [comment]
I would need the full log to do anything with this.

**Comment by kwpugh** [comment]
Nothing I can do with this without a full log.
